version: "3"

x-defaults: &defaults
  volumes: &default-volume-config
    - /var/khala-dev-node/prb_data:/var/data

services:
  pruntime:
    image: phalanetwork/phala-pruntime
    container_name: pruntime
    hostname: pruntime
    ports:
     - "8000:8000"
    devices:
       - /dev/isgx
    environment:
     - EXTRA_OPTS=--cores=2 --checkpoint-interval=43200
     - ROCKET_ADDRESS=0.0.0.0
    volumes:
     - /var/khala-pruntime-data:/root/data
